name: Despliegue seguro de HTML/JS
 
on:
  push:
    branches: ["main"] # Se ejecuta al subir cambios a main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      # --- AQUÍ SE INYECTAN LAS VARIABLES ---
      - name: Inyectar variables en el código
        env:
          VALOR_API_URL: ${{ secrets.API_URL }}
          VALOR_API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Reemplaza los marcadores en tu archivo script.js con los valores reales
          sed -i "s|___VALOR_API_URL___|${VALOR_API_URL}|g" js/configSupabase.js
          sed -i "s|___VALOR_API_KEY___|${VALOR_API_KEY}|g" js/configSupabase.js

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir archivos para desplegar
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Sube la carpeta actual (con el script.js ya modificado)

      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4